/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Job {
    id: string;
    title: string;
    description: string;
    platform: string;
    jobType: string;
    url: string;
    status: string;
    assignedTo: string;
    result: string;
    earned: number;
    foundAt: string;
    completedAt: string;
}
export interface Goal {
    name: string;
    target: number;
    saved: number;
    emoji: string;
}
export interface Skill {
    agent: string;
    skillName: string;
    score: number;
    jobsDone: number;
}
export interface EarningEntry {
    jobId: string;
    amount: number;
    currency: string;
    wallet: string;
    loggedAt: string;
}
export interface Lesson {
    agent: string;
    jobId: string;
    lesson: string;
    learnedAt: string;
}
export interface LogEntry {
    timestamp: string;
    agent: string;
    message: string;
    level: string;
}
export interface backendInterface {
  getJobs(): Promise<Job[]>;
  getGoals(): Promise<Goal[]>;
  getSkills(): Promise<Skill[]>;
  getEarnings(): Promise<EarningEntry[]>;
  getLessons(agentName: string): Promise<Lesson[]>;
  getTotalEarned(): Promise<bigint>;
  getActivityLog(): Promise<LogEntry[]>;
  getWalletPrincipal(): Promise<string>;
  runCycle(): Promise<string>;
  setClaudeApiKey(key: string): Promise<void>;
  addJob(title: string, desc: string, platform: string, jobType: string, url: string): Promise<void>;
  _initializeAccessControlWithSecret(adminToken: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    getJobs(): Promise<Job[]> { return (this.actor as any).getJobs(); }
    getGoals(): Promise<Goal[]> { return (this.actor as any).getGoals(); }
    getSkills(): Promise<Skill[]> { return (this.actor as any).getSkills(); }
    getEarnings(): Promise<EarningEntry[]> { return (this.actor as any).getEarnings(); }
    getLessons(agentName: string): Promise<Lesson[]> { return (this.actor as any).getLessons(agentName); }
    getTotalEarned(): Promise<bigint> { return (this.actor as any).getTotalEarned(); }
    getActivityLog(): Promise<LogEntry[]> { return (this.actor as any).getActivityLog(); }
    getWalletPrincipal(): Promise<string> { return (this.actor as any).getWalletPrincipal(); }
    runCycle(): Promise<string> { return (this.actor as any).runCycle(); }
    setClaudeApiKey(key: string): Promise<void> { return (this.actor as any).setClaudeApiKey(key); }
    addJob(title: string, desc: string, platform: string, jobType: string, url: string): Promise<void> { return (this.actor as any).addJob(title, desc, platform, jobType, url); }
    _initializeAccessControlWithSecret(adminToken: string): Promise<void> { return (this.actor as any)._initializeAccessControlWithSecret(adminToken); }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
